# Generated by Django 4.2.5 on 2023-09-09 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ad",
            options={"verbose_name": "Объявление", "verbose_name_plural": "Объявления"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AddField(
            model_name="ad",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="abs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата и время создания"
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="ad",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="ads", verbose_name="Изображение"
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Цена"
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="title",
            field=models.CharField(default="", max_length=250, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="comment",
            name="ad",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ads.ad",
                verbose_name="Объявление",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="create_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата и время создания"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="text",
            field=models.CharField(
                default="", max_length=1500, verbose_name="Название"
            ),
        ),
    ]
