# Generated by Django 4.2.5 on 2023-09-24 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0002_alter_ad_options_alter_comment_options_ad_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="create_at",
        ),
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата и время создания",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ad",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время создания"
            ),
        ),
    ]
